### ISSUE TITLE
tf2 64 bit

### ISSUE THREAD

**Issue by Sticyboy** [ByMynix/TeaInjector#4]
tf2's new 64 bit wont allow me (or others) to inject into tf2

**Comment by e5x1** [comment]
downgrade to 32bit
tutorial on how to do it: https://www.youtube.com/watch?v=cj6dj8V3sRU

**Comment by Sticyboy** [comment]
thank you it works

**Comment by URADIAL50** [comment]
the problem is when you do the steps without replacing it. it requires files you need to replace which obviously doesn't work 
also there is still no public cheat dlls 64bit in the internet
which is also a problem
